"""initial migration

Revision ID: 3f0dfcf5d4be
Revises: 
Create Date: 2023-12-06 16:31:18.865606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f0dfcf5d4be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_request', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
